# Generated by Django 2.1.7 on 2019-05-30 12:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrgAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=40)),
                ('del_ind', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'ORG_ADDRESS',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrgAttributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attr_name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=40)),
                ('del_ind', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'ORG_ATTRIBUTES',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrgAttrMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_id', models.CharField(max_length=8)),
                ('value', models.CharField(max_length=20)),
                ('attr_def', models.BooleanField(default=False)),
                ('del_ind', models.BooleanField(default=False)),
                ('attr_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dbLayer.OrgAttributes')),
            ],
            options={
                'db_table': 'ORG_ATTR_MAP',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrgClients',
            fields=[
                ('client', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=30)),
                ('del_ind', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'ORG_CLIENTS',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrgCompanies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.CharField(max_length=8)),
                ('name1', models.CharField(max_length=20)),
                ('name2', models.CharField(max_length=20)),
                ('del_ind', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dbLayer.OrgClients')),
            ],
            options={
                'db_table': 'ORG_COMPANIES',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrgCostCtr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_ctr', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=40)),
                ('del_ind', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dbLayer.OrgClients')),
            ],
            options={
                'db_table': 'ORG_COST_CTR',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrgGlAcc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gl_account', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=40)),
                ('del_ind', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dbLayer.OrgClients')),
            ],
            options={
                'db_table': 'ORG_GL_ACC',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrgModel',
            fields=[
                ('node', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('parent_node', models.UUIDField(default=None, null=True)),
                ('map_id', models.CharField(max_length=8)),
                ('del_ind', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dbLayer.OrgClients')),
            ],
            options={
                'db_table': 'ORG_MODEL',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrgNames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('root_node', models.UUIDField(null=True, unique=True)),
                ('del_ind', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dbLayer.OrgClients')),
            ],
            options={
                'db_table': 'ORG_NAMES',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrgNodeTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_type', models.CharField(max_length=8)),
                ('description', models.CharField(max_length=30)),
                ('del_ind', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dbLayer.OrgClients')),
            ],
            options={
                'db_table': 'ORG_NODETYPES',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrgPGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pgroup_id', models.CharField(max_length=8)),
                ('description', models.CharField(max_length=30)),
                ('del_ind', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dbLayer.OrgClients')),
            ],
            options={
                'db_table': 'ORG_PGROUP',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrgPorg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porg_id', models.CharField(max_length=8)),
                ('description', models.CharField(max_length=30)),
                ('del_ind', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dbLayer.OrgClients')),
            ],
            options={
                'db_table': 'ORG_PORG',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrgUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_id', models.CharField(max_length=8)),
                ('user_id', models.CharField(max_length=12)),
                ('name1', models.CharField(max_length=20)),
                ('name2', models.CharField(max_length=20, null=True)),
                ('del_ind', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dbLayer.OrgClients')),
            ],
            options={
                'db_table': 'ORG_USERS',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='orgmodel',
            name='node_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dbLayer.OrgNodeTypes'),
        ),
        migrations.AddField(
            model_name='orgattrmap',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dbLayer.OrgClients'),
        ),
        migrations.AddField(
            model_name='orgattributes',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dbLayer.OrgClients'),
        ),
        migrations.AddField(
            model_name='orgaddress',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dbLayer.OrgClients'),
        ),
        migrations.AlterUniqueTogether(
            name='orgusers',
            unique_together={('client', 'user_id')},
        ),
        migrations.AlterUniqueTogether(
            name='orgporg',
            unique_together={('client', 'porg_id')},
        ),
        migrations.AlterUniqueTogether(
            name='orgpgroup',
            unique_together={('client', 'pgroup_id')},
        ),
        migrations.AlterUniqueTogether(
            name='orgnodetypes',
            unique_together={('client', 'node_type')},
        ),
        migrations.AlterUniqueTogether(
            name='orgnames',
            unique_together={('client', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='orgmodel',
            unique_together={('client', 'map_id')},
        ),
        migrations.AlterUniqueTogether(
            name='orgglacc',
            unique_together={('client', 'gl_account')},
        ),
        migrations.AlterUniqueTogether(
            name='orgcostctr',
            unique_together={('client', 'cost_ctr')},
        ),
        migrations.AlterUniqueTogether(
            name='orgcompanies',
            unique_together={('client', 'company_id')},
        ),
        migrations.AlterUniqueTogether(
            name='orgattributes',
            unique_together={('client', 'attr_name')},
        ),
        migrations.AlterUniqueTogether(
            name='orgaddress',
            unique_together={('client', 'address')},
        ),
    ]
