# Generated by Django 2.1.7 on 2019-06-03 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbLayer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgmodel',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
